# Fig1-C-E-get-general-stats-proteome-coverage
require(data.table)
library(VennDiagram)
library("RColorBrewer")


#___ protein groups 
# the trimmed proteins groups files are generated by this script: code-to-generate-trimmed-protGroups-files.R
# download protein groups files from https://www.ebi.ac.uk/pride/archive/projects/PXD013455
tmp <- fread( "cellLines-proteinGroups.txt", quote = "\"", header = TRUE, sep = "\t", stringsAsFactors = FALSE,  na.strings = c(NA, "NA", "NaN"), strip.white = T )
#
tmp <- data.frame(tmp)
tmp <- tmp[ , -1]  
tmp <- tmp[ , c(1:8, grep("iBAQ.", colnames(tmp)))]
colnames(tmp)  <- paste("cellLines", colnames(tmp), sep = "-")
tmp$LeadingProtein <- sub(";.*", "", tmp$`cellLines-Majority.protein.IDs`)
#
tmp2 <- fread( "tumours-proteinGroups.txt", quote = "\"", header = TRUE, sep = "\t", stringsAsFactors = FALSE,  na.strings = c(NA, "NA", "NaN"), strip.white = T )
# convert it to dataframe - otherwise data.frame style of subsetting does not work
tmp2 <- data.frame(tmp2)
tmp2 <- tmp2[ , -1]  
colnames(tmp2) <- paste("tumours", colnames(tmp2), sep="-")
# tmp2 <- tmp2[ , c(1:8, grep("iBAQ.", colnames(tmp2)))]
tmp2$LeadingProtein <- sub(";.*", "", tmp2$`tumours-Majority.protein.IDs`)

###
### merge by leading protein
prot <- merge(tmp, tmp2, by.x = "LeadingProtein", by.y = "LeadingProtein", all = T)

uniprot.map <- read.table( "HUMAN_9606_idmapping_selected.tab", header = T, sep = "\t", fill = T, stringsAsFactors = FALSE)
uniprot.map <- uniprot.map[ , c(1, 19)]

###
x.cellLines <- unique(trimws(unlist(strsplit(tmp$`cellLines-ENSG`, ";")), which = "both"))
y.tumours <- unique(trimws(unlist(strsplit(tmp2$`tumours-ENSG`, ";")), which = "both"))
#
z.all <- unique(c(x.cellLines, y.tumours))

z.uniprot <- unique(trimws(  unlist(strsplit(uniprot.map$Ensembl, ";")) , which = "both"  )  )

# write.table(unique( c(x.cellLines, y.tumours)), file = "ENSGgeneUniverse.txt", sep = "\t", row.names = T, col.names=NA, quote = F,na ="")
# write.table(unique( y.tumour.unique), file = "ENSG_tumourUniquegenes.txt", sep = "\t", row.names = T, col.names=NA, quote = F,na ="")

dev.off()
vp <- venn.diagram(  
  list(  b= c(z.all,1),a =z.uniprot )
  ,
  fill = c( "#8dd3c7" , "#fccde5"),  alpha = c( 1,1)
  , filename = NULL, 
  margin = 0.1, cat.fontface = "bold", print.mode = FALSE, category.names = FALSE,  ext.line.lwd = NA, ext.pos = 30, ext.dist = 0.1, cat.col= FALSE, cex = 1.5 ); 
grid.draw(vp)

dev.off()
vp <- venn.diagram(  
  list(  b= z.all,a =z.uniprot )
  ,
  
  
  fill = c( "#0570b0", "#238b45" ),  alpha = c( 0.71, 0.71)
  , filename = NULL, 
  margin = 0.1, cat.fontface = "bold", print.mode = c("raw", "percent"), category.names = FALSE,  ext.line.lwd = NA, ext.pos = 30, ext.dist = 0.1, cat.col= FALSE, cex = 1.5 ); 
grid.draw(vp)

dev.off()
vp <- venn.diagram(  
  list( c = z.all, a =x.cellLines, b= y.tumours )
  ,
  fill = c( "#969696", "#e5f5e0", "#9ecae1" ),  alpha = c(0.25, 0.71, 0.71), filename = NULL, 
  margin = 0.1, cat.fontface = "bold", print.mode = c("raw", "percent"), category.names = FALSE,  ext.line.lwd = NA, ext.pos = 30, ext.dist = 0.1, cat.col= FALSE, cex = 1.5 ); 
grid.draw(vp)


##################################################
####_____main analysis on protein groups_____#####
####_________________________________________#####
##################################################
tmp  <-  fread( "proteinGroups.txt", quote = "\"", header = TRUE, sep = "\t", stringsAsFactors = FALSE,  na.strings = c(NA, "NA", "NaN"), strip.white = T) # comment.char = "#",
tmp <- data.frame(tmp)
#
data <- tmp[ tmp[, "Reverse"] != "+", ]
data <- data[ data[, "Potential.contaminant"] != "+", ]
data <- data[ data[, "Only.identified.by.site"] != "+", ]
rm(tmp)
# get stats - identified proteins, genes
message( paste("Total number of idnetified protein groups:", nrow(data)))

# here run the map_uniprot_ensg.R script to map uniprot accessiont to gene IDs
#####
####__ be patient this loop will take a moment to complete!
#####
# quantified proteins, genes, i.e. at least 2 unique peptides per protein group 
# hist((data$Unique.peptides), xlim=c(0,10), breaks = 5000)
data <- data[ data[, "Unique.peptides"] > 1, ]
# write.table(data, file = "proteinGroups_filtered_2pepPerProt.txt", sep = "\t", row.names = T, col.names=NA, quote = F,na ="")
#
message( paste("Total number of idnetified protein groups:", nrow(data)))
message( paste("Number of genes (proteins mapping to ENS genes):" ), length(unique(unlist(strsplit(data$ENSG, split = ";"))))-1  ) 
################################################################
rm(data.to.map, uniprot.map, x, all.genes, all.genes.names, i )

#############################
#############################
#############################
# do the number of quants per cell line plot quant plot
ibaq.data <-  data[ ,c( grep("^iBAQ..", colnames(data))), drop =FALSE ]
row.names(ibaq.data) <- data$Majority.protein.IDs
######

## remove the kinome data
ibaq.data <-  ibaq.data[ ,c( grep("kinome*", colnames(ibaq.data), invert = TRUE)), drop =FALSE ]
# get number of cell lines/  tumour samples
assays <- sapply(strsplit(colnames(ibaq.data), "_"), function(y){y[1]})
table(assays)
unique(assays)
#
# remove all non cell lines data
assays.to.rm <- c("MCF10A", "HEK293","iBAQ.FallopianTubeEpithelialCells", "iBAQ.HEYA8", "iBAQ.Tumour.")
ibaq.data <-  ibaq.data[ , grep(paste(assays.to.rm, collapse="|"),  colnames(ibaq.data) , invert = TRUE), drop=FALSE]
######
my.cells <-  sapply(strsplit(colnames(ibaq.data), "_"), "[",1 )
my.cells <- sub("iBAQ." , "", my.cells)
my.cells <- toupper(my.cells)
my.cells <- sub("RXF393L", "RXF393", my.cells)
my.cells <- gsub("\\.", "", my.cells)

message( paste("Number of unique cell lines included in dataset:", length(unique(my.cells))))
#############

ibaq.data[ ibaq.data == 0] <- NA
# plot number of ids per study
na_count <- sapply(ibaq.data, function(y) sum(!is.na(y))  ) #
na_count <- as.data.frame(na_count)
# na_count <- data.frame(na_count[-1,])
na_count <- na_count[order(na_count$na_count, decreasing = FALSE), ,drop=FALSE]
head(na_count,10)
tail(na_count, 10)
median(na_count$na_count)
mean(na_count$na_count)
#
#
ibaq.data$protein.names <- row.names(ibaq.data)
tmp.melt <- melt(data = ibaq.data, value.name = "iBAQ", id = "protein.names") #, id = "prot.name"
tmp.melt[ tmp.melt == 0  ] <- NA
tmp.melt <- tmp.melt[ !is.na(tmp.melt$iBAQ) , ]
tmp.melt$variable <-  gsub("iBAQ.", "",tmp.melt$variable)
tmp.melt$cellLine <-  gsub("_.*", "",tmp.melt$variable)
tmp.melt$study <- gsub( ".*_", "", tmp.melt$variable) 
tmp.melt$replicate <- sub("^(.*)[_].*", "\\1", tmp.melt$variable)
##
#
unique(tmp.melt$cellLine)
unique(tmp.melt$study)

quant.cell.type <-  data.frame(table(tmp.melt$variable))
quant.cell.type$cellLine <- gsub("_.*", "",quant.cell.type$Var1)
quant.cell.type

means.by.cell<-ddply(quant.cell.type, .(cellLine), summarize, mean=mean(Freq), SD = sd(Freq))

means.by.cell <-  means.by.cell[order(means.by.cell$mean, decreasing = F), ]

#
op <- par(mar=c(6,4,4,1))
foo <- barplot(means.by.cell$mean, col = "#4393c3", border=NA, xlab="",names.arg = means.by.cell$cellLine, las =2, cex.names  = 0.75, horiz = F)
# axis(1, at=foo, labels= means.by.cell$cellLine, las=3)
arrows(x0=foo,y0=means.by.cell$mean+means.by.cell$SD,y1 =means.by.cell$mean-means.by.cell$SD ,angle=90,code=3,length=0.025, col = "black")
op <- par(mar=c(6,6,6,1))
##
###########################################################################################
#####
##### tumours data
#####
#######################################
######################################
####___Obtain general stats______#####
####___MS/MS, scans, etc_________#####
######################################
tmp <- read.table( "./tumours-summary.txt", quote = "\"", header = TRUE, sep = "\t", stringsAsFactors = FALSE,  na.strings = c(NA, "NA", "NaN"), strip.white = T)
# total number of MS/MS
message( paste("Total number of MS/MS spectra is:", tmp$MS.MS[nrow(tmp)]) ,"\r",appendLF=FALSE)
# total number of identified MS2
message( paste("Number of IDENTIFIED MS/MS spectra is:", tmp$MS.MS.Identified[nrow(tmp)] ))
dataset <-  sapply(strsplit(tmp$Experiment, "_"), "[",3 )
tmp$Experiment <- dataset
aggregate(MS.MS ~ Experiment ,data= tmp,sum,na.rm=T)
rm(tmp)
#
###
##################################################
####__get number of pepetides and FDR rate___#####
####_________________________________________#####
##################################################
# this might take a minute or so as peptides file is large
tmp <- fread( "tumours-peptides.txt", quote = "\"", header = TRUE, sep = "\t", stringsAsFactors = FALSE,  na.strings = c(NA, "NA", "NaN"), strip.white = T )
#
# convert it to dataframe - otherwise data.frame style of subsetting does not work
tmp <- data.frame(tmp)
data <- tmp[ tmp[, "Potential.contaminant"] != "+", ]
# get the reverse hits
rev <- data[ data[,"Reverse" ] == "+", ]
data <- data[ data[,"Reverse" ] != "+", ]
message( paste("Number of peptide ids:", nrow(data)))
message( paste("Peptide level FDR is:", (nrow(rev)/nrow(data))*100, "%" ))
rm(tmp, data, rev)
####
##

##################################################
####_____main analysis on protein groups_____#####
####_________________________________________#####
##################################################
tmp  <-  read.table( "tumours-proteinGroups.txt", quote = "\"", header = TRUE, sep = "\t", stringsAsFactors = FALSE,  na.strings = c(NA, "NA", "NaN"), strip.white = T) # comment.char = "#",
#
data <- tmp[ tmp[, "Reverse"] != "+", ]
data <- data[ data[, "Potential.contaminant"] != "+", ]
data <- data[ data[, "Only.identified.by.site"] != "+", ]
rm(tmp)
#
# get some stats - identified proteins, genes
message( paste("Total number of idnetified protein groups:", nrow(data)))
# perform protein ID  to ensmbl gene IDs and Gene names mapping here 

message( paste("Number of genes (proteins mapping to ENS genes):" ), length(unique(unlist(strsplit(data$ENSG, split = ";"))))-1  ) 
###############################     
###############################
###############################
###############################
data <- data[ , c(1:4,10:11, 16, 2583,  grep("^Intensity\\.L\\.", colnames(data)), grep( "Intensity.*_Zhang_.*$", colnames(data)), grep("^iBAQ\\.L\\.", colnames(data)),grep( "iBAQ.*_Zhang_.*$", colnames(data)) )] 
# quantified proteins, genes, i.e. at least 2 unique peptides per protein group 
data <- data[ data[, "Unique.peptides"] > 1, ]

# do the number of quants per cell line plot quant plot
int.data <- data[ ,c( grep("Intensity..", colnames(data))), drop =FALSE ] row.names(int.data) <- data$Majority.protein.IDs
colnames(int.data)
message( paste("Number of nonmalignant samples included in dataset:", length(grep("\\.Nonmalignant\\.", colnames(int.data)))   ))
# 

ibaq.data <-  data[ ,c( grep("^iBAQ..", colnames(data))), drop =FALSE ]
row.names(ibaq.data) <- data$Majority.protein.IDs
## remove 
ibaq.data <-  ibaq.data[ ,
                         -c( grep("_PulsedSILAC", colnames(ibaq.data)), grep("iBAQ.L.mix", colnames(ibaq.data)), grep("iBAQ.L.Nonmalignant.", colnames(ibaq.data)), grep("L.superSILACmix", colnames(ibaq.data)), grep("iBAQ.L.Tumour.xxxxBC", colnames(ibaq.data)))
                         , drop =FALSE ]

int.data <-  int.data[ ,
                       -c( grep("_PulsedSILAC", colnames(int.data)), grep("Intensity.L.mix", colnames(int.data)), grep("Intensity.L.Nonmalignant.", colnames(int.data)), grep("L.superSILACmix", colnames(int.data)), grep("Intensity.L.Tumour.xxxxBC", colnames(int.data)))
                       , drop =FALSE ]

message( paste("Number of tumour samples included in dataset:", length(grep("Tumour", colnames(ibaq.data)))  ))
#############